# Generated by Django 3.1.3 on 2020-11-02 15:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, null=True)),
                ('phone', models.CharField(default='', max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 21, 18, 57, 874587))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 21, 18, 57, 874587))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 21, 18, 57, 875585))),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.charger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.profile')),
            ],
        ),
    ]
