# Generated by Django 3.1.3 on 2020-11-02 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 21, 24, 35, 963560)),
        ),
        migrations.AlterField(
            model_name='charger',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 21, 24, 35, 962564)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 2, 21, 24, 35, 957577)),
        ),
    ]
